//
//  QuizModels.swift
//  TheQuiz
//
//  Created by Jan Osmančík on 22.03.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Quiz {
    // MARK: Use cases
    enum Detail {
        struct Request {}
        struct Response {}
        struct ViewModel {}
    }
}

struct QuizModel: Equatable {
    static func == (lhs: QuizModel, rhs: QuizModel) -> Bool {
        lhs.id == rhs.id && lhs.title == rhs.title && lhs.questions == rhs.questions
    }
    
    let id: String
    let title: String
    var questions: [QuestionModel]
}

struct QuestionModel: Equatable {
    let id: String
    let text: String
    var answered: Bool = false
    let allowsMultipleAnswers: Bool
    var answers: [AnswerModel]
    var selectedAnswers: [AnswerModel] = []
    
    mutating func deselectAllAnswers() {
        for index in answers.indices {
            answers[index].selected = false
        }
    }
}

struct AnswerModel: Equatable {
    let id: String
    let text: String
    var selected: Bool = false 
    let correct: Bool
}

