//
//  QuizRouter.swift
//  TheQuiz
//
//  Created by Jan Osmančík on 22.03.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class QuizRouter: NSObject, QuizRoutingLogic, QuizDataPassing {
    weak var viewController: QuizViewController?
    var dataStore: (any QuizDataStore)?
    
    // MARK: Routing
    
//    func routeToEvaluation()
//    {
//        guard let dataStore = dataStore else { return }
//        let destinationVC = EvaluationViewController()
//        if let viewController = viewController, var destinationDS = destinationVC.router?.dataStore {
//            passDataToEvaluation(source: dataStore, destination: &destinationDS)
//            navigateToEvaluation(source: viewController, destination: destinationVC)
//        }
//    }
//    
//    // MARK: Navigation
//    
//    func navigateToEvaluation(source: QuizViewController, destination: EvaluationViewController) {
//        source.show(destination, sender: nil)
//    }
//    
//    // MARK: Passing data
//    
//    func passDataToEvaluation(source: QuizDataStore, destination: inout EvaluationDataStore) {
//        destination.quiz = source.quiz
//    }
}
