//
//  DashboardModels.swift
//  TheQuiz
//
//  Created by Jan Osmančík on 22.03.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Dashboard {
    // MARK: Use cases
    enum Quiz {
        enum List
        {
            struct Request {}
            struct Response {
                let error: Error?
                let result: [QuizModel]?
            }
            struct ViewModel {
                let quizList: [QuizModel]
            }
        }
        
        enum Detail {
            struct Request {
                let id: String
            }
            struct Response{
                let error: Error?
                let result: QuizModel?
            }
            struct ViewModel {
                let quiz: QuizModel
            }
        }
    }
}
