//
//  DashboardWorker.swift
//  TheQuiz
//
//  Created by Jan Osmančík on 22.03.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Combine

class DashboardWorker {
    func fetchMockQuizData() -> AnyPublisher<QuizModel, Error> {
            return Future<QuizModel, Error> { promise in
                DispatchQueue.global().async {
                    let mockQuizData = QuizMockData().mockQuiz
                    promise(.success(mockQuizData))
                }
            }
            .eraseToAnyPublisher()
        }
}
