//
//  DashboardRouter.swift
//  TheQuiz
//
//  Created by Jan Osmančík on 22.03.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DashboardRouter: NSObject, DashboardRoutingLogic, DashboardDataPassing {
    weak var viewController: DashboardViewController?
    var dataStore: DashboardDataStore?
    
    // MARK: Routing
    
    func routeToQuiz() {
        guard let dataStore = dataStore else { return }
        let destinationVC = QuizViewController()
        if let viewController = viewController, var destinationDS = destinationVC.router?.dataStore {
            passDataToQuizScene(source: dataStore, destination: &destinationDS)
            navigateToQuiz(source: viewController, destination: destinationVC)
        }
    }
    
    
    // MARK: Navigation
    
    func navigateToQuiz(source: DashboardViewController, destination: QuizViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToQuizScene(source: DashboardDataStore, destination: inout any QuizDataStore) {
        destination.quiz = source.quiz
    }
}
